export IMAGE_REPO="zcloudws"
export IMAGE_NAME="meteor-build"
export IMAGE_TAG="1.5.4.1"
export INIT_COMMAND_VARS="export NODE_TLS_REJECT_UNAUTHORIZED=0"
export PACKAGES="build-essential python2"
#export ENV_VARS="build-essential python2"
