export IMAGE_REPO="zcloudws"
export IMAGE_NAME="meteor-node-mongodb-runtime"
export IMAGE_TAG="1.6.1.4"
export INIT_COMMAND_VARS="export NODE_TLS_REJECT_UNAUTHORIZED=0"
export PACKAGES="python2"
export METEOR_TOOL_VERSION="1.6.1_4"
