export IMAGE_REPO="zcloudws"
export IMAGE_NAME="meteor-node-runtime"
export IMAGE_TAG="1.6.1.4"
export INIT_COMMAND_VARS="export NODE_TLS_REJECT_UNAUTHORIZED=0"
export PACKAGES="python2"
#export ENV_VARS="build-essential python2"
