name: GLPI Release
on:
  workflow_dispatch:
    inputs:
        glpiRevision:
            description: 'GLPI branch revision, tag or commit hash'
            required: true
            default: 'main'
            type: string
        glpiTag:
            description: 'Tag for docker image'
            required: true
            default: 'latest'
            type: string

env:
  IMG: zcloudws/glpi:${{ inputs.glpiTag }}
jobs:
  operator-build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build GLPI image
        env:
          IMG: ${{ env.IMG }}
        run: |
          cd glpi
          echo "GLPI image tag: $IMG"
          echo "GLPI source revision: ${{ inputs.glpiRevision }}"
          docker build -t "$IMG" --build-arg GLPI_SOURCE_REVISION=${{ inputs.glpiRevision }} .
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: docker push "${{ env.IMG }}"

