name: Meteor Runtime images

on:
  workflow_dispatch:
    inputs:
      meteorVersions:
        description: 'Meteor version(s)'
        required: true
        default: '3.0.1'
        type: string
jobs:
  RebuildMeteorRuntimeImages:
    name: Rebuild meteor runtime image ${{ inputs.meteorVersions }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rebuild meteor runtime image
        run: cd meteor-tools && ./rebuild-runtime-images.sh "${{ inputs.meteorVersions }}"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push meteor runtime image
        run: cd meteor-tools && ./push-runtime-images.sh "${{ inputs.meteorVersions }}"
