name: Meteor images

on:
  workflow_dispatch:
    inputs:
      meteorVersion:
        description: 'Meteor version'
        required: true
        default: '2.12'
        type: string
jobs:
  createReleaseTag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build meteor image
        run: cd meteor-tools && ./build-all.sh "${{ inputs.meteorVersion }}"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push meteor image
        run: cd meteor-tools && ./push-all.sh "${{ inputs.meteorVersion }}"
